### ISSUE TITLE
Options prop

### ISSUE THREAD

**Issue by mccabemj** [abdennour/react-csv#109]
Based on the following issues/PR
#74 
#42 
#78 
#94 
#93 
#102 
These are all pretty simple to implement, but keep needing new props to be added. For example, the already merged/implemented 'separator'

Why not have a new 'options' prop containing all of these
options={ separator: ":", noHeaders: true, encoding: "ASCII-8BIT", enclosingCharacter: "$" }

Over time, we can simply add new options to make easy enough changes. This feature could be added in a new big release (1.1.0) along with closing down some long standing issues.

@abdennour @mriccid thought I'd run this by you before going ahead and implementing

**Comment by abdennour** [comment]
like the idea. @mccabemj

**Comment by mriccid** [comment]
I'm not sure that I can see the benefit in having an `options` prop rather than just using separate props for each new configuration. That way they can be more easily (IMO) validated and documented. I don't see a problem in adding new props either, as long as there is effort put in to keep the number of props and the scope of the props to a limit so that the API doesn't become needlessly complex.

In my opinion it is also easier for users of the library to digest a prop of `separator`, rather than an `options` object prop as it is simpler and also more in line with convention. 

I can understand the benefit in having less props in that it would make the component potentially easier to use, but I don't think I can see how it would benefit the complexity of the component's internal implementation. In fact, I can see it potentially being more complex as you would have to check for the existence of the options object and then check the existence/value of a field on that object.
