### ISSUE TITLE
Unable to download CSV in Microsoft edge

### ISSUE THREAD

**Issue by aswin1689** [abdennour/react-csv#25]
If I try to download CSV on edge browser, it does nothing. Either browser crashes or just opens a new blank tab in few edge versions. Can you please fix this issue for us. Thanks.

**Comment by dnieh** [comment]
Looked into this and this library simulates a file download by navigating to the data uri. You can see that here: https://github.com/abdennour/react-csv/blob/master/src/components/Link.js#L29

The problem is that Edge/IE doesn't support navigating to a data uri. See: https://stackoverflow.com/questions/33154646/data-uri-link-a-href-data-doesnt-work-in-microsoft-edge

**Comment by dnieh** [comment]
Found a solution for IE11+: https://stackoverflow.com/a/27699027

**Comment by bradenpowers** [comment]
I am running into this issue as well.  A fix would be great!

**Comment by mriccid** [comment]
I've created a fork (https://github.com/mriccid/react-csv) which solves this using `navigator.msSaveBlob`. 

Please note that I haven't written tests for these changes yet, so it's not not ready to be used. Feel free to have a look at the changes anyway.

**Comment by toolaugh** [comment]
@dnieh  It not run with firefox too ... help me

**Comment by neuhausneuhaus** [comment]
@mriccid Make a PR

**Comment by minotaurrr** [comment]
@toolaugh it runs fine on firefox.. maybe check again?

Has there been a fix for this yet?

**Comment by toolaugh** [comment]
@minotaurrr it works well, thanks

**Comment by nieud** [comment]
Hello, this is still not working on Edge for me.

Is there any update planified ?

Thanks

**Comment by KingstonDuo** [comment]
@mriccid 's fork has fixed the IE problem for me. You should make a pull request!

**Comment by mriccid** [comment]
@KingstonDuo I would like to, but I am worried that my fork deviates too much from the original implementation. I will try to tidy it up, fix any tests and make a PR soon.

**Comment by brammitch** [comment]
I think this is a great project and would like to see this issue fixed. 

@mriccid Do you still intend to work on your fork at all?

I wonder if @abdennour is still maintaining this project? I see there is already another pull request that fixes this issue that has been waiting for merge since October.

**Comment by abdennour** [comment]
Hello guys, Hello @brammitch  . I want to share the access to not block the community. Any recommendation how to do that ?

**Comment by abdennour** [comment]
@mriccid  and @bmuenzenmeyer are added as collaborators. Please, I need your npm ID to publish changes as well?

**Comment by abdennour** [comment]
@brammitch or anyone: Please notify me [here](http://in.abdennoor.com) by a message for any request.

**Comment by brammitch** [comment]
Thanks and good luck to you!

**Comment by mriccid** [comment]
@abdennour are you able to add me to the collaborators list on NPM so that I can publish 1.0.10? Or could you or @bmuenzenmeyer please update the version?

**Comment by minotaurrr** [comment]
waiting for npm publish!

**Comment by abdennour** [comment]
@mriccid  I added you as an NPM contributor. Please go ahead!

**Comment by mriccid** [comment]
`react-csv@1.0.10` has been published, which fixes this issue. Thanks to all involved.
