### ISSUE TITLE
TypeError when including library in a test

### ISSUE THREAD

**Issue by matejstrasek** [abdennour/react-csv#9]
I get this when including <CSVLink> component in a test. 
Using WebPack, Karma and PhantomJS.

```
TypeError: undefined is not a function (evaluating 'Object.assign(_metaProps.defaultProps, defaultProps)')
  at /usr/src/app/tests/test-bundler.js:136375 <- webpack:///~/react-csv/lib/components/Download.js:74:0
```

**Comment by abdennour** [comment]
@matejstrasek  : "Download" component calls "window.open", then, when you run your test , the page will be reloaded by mounting this component. That's why , it might need to mock "window.open " . Anyway, you can check [the unit-tests of this component](https://github.com/abdennour/react-csv/blob/master/test/ComponentsSpec.js#L118) .

So , this is hypothesis and I hope it will fix your issue . 


 Please check unit-tests

**Comment by matejstrasek** [comment]
The error comes from the library so I have a feeling is more related to this:

> Object.assign is a part of ES2015 and PhantomJs doesn't support ES2015 (actually no browser fully supports it yet).

**Comment by matejstrasek** [comment]
Using object assign polyfill solved the problem.

> https://www.npmjs.com/package/phantomjs-polyfill-object-assign
